### PR TITLE
fix: don't print out expected error

### LINKED ISSUE #966: Failed to get url from Addresses.API TypeError: "t is null"
**Describe the bug**
This is showing up in the logs:

```console
Failed to get url from Addresses.API TypeError: "t is null"
```

It's not fatal, but it shouldnt be there.

**To Reproduce**

1. https://ipfs.io/ipfs/QmZTMSPS7Wk1N6yUFgMRdeXxhQc2uAeLPpQZbn7n2B7VBk/#/welcome
2. Check the dev console

screenshot 2019-02-21 at 17 50 55

### PR DESCRIPTION
**Pull request by hacdias**
Fixes #966 by not printing the error. That's an expected error in that function. We could also make the function receive an `expectsFailure` boolean variable which would tell whether or not to print the error.

License: MIT
Signed-off-by: Henrique Dias <hacdias@gmail.com>

### CODE REVIEW

File: src/bundles/config.js [hunk 1]
```diff
@@ -60,8 +60,7 @@ function getURLFromAddress (name, config) {
   try {
     const address = config.Addresses[name]
     return toUri(address).replace('tcp://', 'http://')
-  } catch (error) {
-    console.log(`Failed to get url from Addresses.${name}`, error)
+  } catch (_) {
```
Comment (olizilla) [inline src/bundles/config.js]: This smothers all errors, which we don't want to do. The error we can ignore is where `config` is undefined or null.

**Comment by hacdias** [comment]
Fixed @olizilla!

**Comment by olizilla** [comment]
I don't *want* to be obsessive (_clearly i am _) about such a tiny change, but this feels like a suprising way to fix this error... As a general pattern that I've got ingrained in my head, always handle the edge cases up front, before letting things flow to the rest of the logic.

```js
function getURLFromAddress (name, config) {
  if (!config) return null
  try {
    const address = config.Addresses[name]
    return toUri(address).replace('tcp://', 'http://')
  } catch (error) {
      console.log(`Failed to get url from Addresses.${name}`, error)
      return null
  }
}
```

**Comment by hacdias** [comment]
@olizilla yeah, that makes sense! Changed. Should've thought about that first

**Comment by olizilla** [comment]
@hacdias pls think about the what you'd  like to read in a change log when you write your PR titles.

`fix: don't print out expected error` won't mean anything to a reader looking at the release notes.
